version: '3.8'

services:

  g2i-guess-game:
    container_name: g2i-guess-game
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:80'
    env_file:
      - .env